apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-ssh
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    "jenkins.io/credentials-description" : "ssh github.com:adamkielar/jenkins-runner"
stringData:
  privateKey: | # Add private key. `cat 'path to your file id_ed25519``
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
  username: # Add github username
