kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-azurefile
provisioner: file.csi.azure.com
mountOptions:
  - uid=1000
  - gid=1000
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  skuName: Standard_LRS